// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElCol: typeof import('element-plus/es')['ElCol']
    ElRow: typeof import('element-plus/es')['ElRow']
    FooterBottom: typeof import('./src/components/FooterBottom.vue')['default']
    FooterTop: typeof import('./src/components/FooterTop.vue')['default']
    HeaderView: typeof import('./src/components/HeaderView.vue')['default']
    FooterBottom: typeof import('./src/components/FooterBottom.vue')['default']
    FooterTop: typeof import('./src/components/FooterTop.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TitleView: typeof import('./src/components/TitleView.vue')['default']
  }
}
