// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export { }

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Breadcrumb: typeof import('./src/components/common/Breadcrumb.vue')['default']
    CartAction: typeof import('./src/components/CartComponents/CartAction.vue')['default']
    CartAS: typeof import('./src/components/CartComponents/components/CartItemComponents/CartAS.vue')['default']
    CartContent: typeof import('./src/components/CartComponents/CartContent.vue')['default']
    CartControl: typeof import('./src/components/CartComponents/components/CartItemComponents/CartControl.vue')['default']
    CartGoods: typeof import('./src/components/CartComponents/components/CartItemComponents/CartGoods.vue')['default']
    CartItem: typeof import('./src/components/CartComponents/components/CartItem.vue')['default']
    CehckboxRadio: typeof import('./src/components/CartComponents/components/CehckboxRadio.vue')['default']
    CehckoutRadio: typeof import('./src/components/CartComponents/components/CehckoutRadio.vue')['default']
    Checkbox: typeof import('./src/components/CartComponents/components/Checkbox.vue')['default']
    CheckboxRadio: typeof import('./src/components/CartComponents/components/CheckboxRadio.vue')['default']
    DeleteChecked: typeof import('./src/components/CartComponents/components/DeleteChecked.vue')['default']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    FooterBottom: typeof import('./src/components/common/FooterBottom.vue')['default']
    FooterTop: typeof import('./src/components/common/FooterTop.vue')['default']
    HeaderView: typeof import('./src/components/common/HeaderView.vue')['default']
    Midal: typeof import('./src/components/CartComponents/components/Midal.vue')['default']
    ModalButton: typeof import('./src/components/CartComponents/components/ModalButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SwiperView: typeof import('./src/components/HomeComponents/SwiperView.vue')['default']
    TitleView: typeof import('./src/components/common/TitleView.vue')['default']
  }
}
