// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Breadcrumb: typeof import('./components/common/Breadcrumb.vue')['default']
    CartAction: typeof import('./components/CartComponents/CartAction.vue')['default']
    CartAS: typeof import('./components/CartComponents/components/CartItemComponents/CartAS.vue')['default']
    CartContent: typeof import('./components/CartComponents/CartContent.vue')['default']
    CartControl: typeof import('./components/CartComponents/components/CartItemComponents/CartControl.vue')['default']
    CartGoods: typeof import('./components/CartComponents/components/CartItemComponents/CartGoods.vue')['default']
    CartItem: typeof import('./components/CartComponents/components/CartItem.vue')['default']
    CategoryItem: typeof import('./components/cate/CategoryItem.vue')['default']
    CategoryList: typeof import('./components/cate/CategoryList.vue')['default']
    CateHead: typeof import('./components/cate/CateHead.vue')['default']
    Checkbox: typeof import('./components/CartComponents/components/Checkbox.vue')['default']
    CheckboxRadio: typeof import('./components/CartComponents/components/CheckboxRadio.vue')['default']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    FooterBottom: typeof import('./components/common/FooterBottom.vue')['default']
    FooterTop: typeof import('./components/common/FooterTop.vue')['default']
    HeaderView: typeof import('./components/common/HeaderView.vue')['default']
    KindItem: typeof import('./components/CartComponents/components/CartItemComponents/KindItem.vue')['default']
    ModalButton: typeof import('./components/CartComponents/components/ModalButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SwiperView: typeof import('./components/common/SwiperView.vue')['default']
    TitleView: typeof import('./components/common/TitleView.vue')['default']
  }
}
